# Generated by Django 5.2.3 on 2025-06-18 14:41

import django.db.models.deletion
import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('desc', models.TextField(blank=True)),
                ('status', models.BooleanField(default=0, verbose_name=goods.models.Goods.Status)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('cats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category')),
            ],
        ),
    ]
